INSERT INTO STOCK_PRICE_DETAILS (STOCK_ID, COMPANY_NAME, COMPANY_PRICE) VALUES (101,'TCS',3000.0);
INSERT INTO STOCK_PRICE_DETAILS (STOCK_ID, COMPANY_NAME, COMPANY_PRICE) VALUES (102,'HCL',1500.0);
INSERT INTO STOCK_PRICE_DETAILS (STOCK_ID, COMPANY_NAME, COMPANY_PRICE) VALUES (103,'SBI',450.0);
INSERT INTO STOCK_PRICE_DETAILS (STOCK_ID, COMPANY_NAME, COMPANY_PRICE) VALUES (104,'HDFC',4500.0);